name: Rust CI

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rustfmt.toml"
      - "rust-toolchain.toml"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/rust.yml"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          cmd-format: "nix develop --command {0}"

      - name: cargo test
        run: nix develop --command cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          cmd-format: "nix develop --command {0}"

      - name: cargo clippy
        run: nix develop --command cargo clippy -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: rustfmt --check
        run: nix develop --command cargo fmt --all --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          cmd-format: "nix develop --command {0}"

      - name: cargo build
        run: nix develop --command cargo build --release
